CREATE TABLE clients (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,    
SSN char (9) NOT NULL UNIQUE,
Fname VARCHAR (100) NOT NULL,
Lname VARCHAR (100) NOT NULL,
DOB date NOT NULL,
address VARCHAR (200) NOT NULL);

CREATE TABLE dependent(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
SSN char (9) NOT NULL,
Fname varchar (80) NOT NULL,
Lname varchar (80) NOT NULL,
relationship varchar (80) NOT NULL,
Foreign Key (SSN) REFERENCES clients (SSN) ON DELETE CASCADE ON UPDATE CASCADE) ;